{
  # AnimalsContainer CONFIG
  ##########################################################################################################################################
  # The following parameters must be set set to define where to look for images and various file types (file derivatives)
  # NOTE: all files attached to an animal must include "_sXXX_" somewhere in the filename, where X is a digit
  
  # image_data_base_dir --> directory to look for images, must contain dirs for each cohort 
  # image_dir_names --> dirs inside each cohort directory that contain different image types, each dir must contain folder for each animal
  # animal_id_prefix --> string that prefixes animal id number (e.g. 'animal' in 'animal67')
  # qupath_subdirs --> directories containing derivative files, should be stored in each animal's qupath project folder
  # align_files_dict --> dictionary mapping qupath subdirs to a list of file suffixes to extract from that folder
  #                         if multiple elements in list, creates seperate pathslist property to align
  #                         first key is the key all others align to, key must be in qupath_subdirs
  # cohorts (list[dict]) --> dictionary for each cohort
  #     cohort_name (str) --> name assigned
  #     id_range (list[int]) --> list of animal ids 
  #     image_dir (str) --> name of dir in image_dir_names containing folders for each animal
  #     abba_projects_by_animal_dir (str) --> path to directory containing a folder for each animal (where qupath data is)
  #     file_derivatives_dirname (None, str) --> optional, if qupath project folder (file derivatives) nested in animal's directory
  ##########################################################################################################################################

  AnimalsContainer: {
    image_data_base_dir: 'D:/ReijmersLab/TEL/slides', 
    image_dir_names: [fullsize, resized], 
    animal_id_prefix: TEL, 

    qupath_subdirs: {
        atlas_mask_dir: atlas_masks,
        geojson_regions_dir: qupath_export_geojson, 
        qupath_project_filepath: project.qpproj,
        abba_states_dir: abba_states, 
        quant_dir: quant, 
        counts_dir: counts, 
        pxToAtlasCoords: qupath_export_pxToAtlasCoords
    },

    align_files_dict: {
      fullsize: [.tif], 
      resized: [.png], 
      geojson_regions_dir: [.geojson],
      atlas_mask_dir: [atlas_mask.tif, leftSide.tif], 
      quant_dir: [nuclei.tif], 
      counts_dir: [region_df.csv, rpdf.csv], 
      pxToAtlasCoords: [pxToAtlasCoords.tsv]
    }, 

    cohorts: [
      {
        cohort_name: cohort2, 
        id_range: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], 
        image_dir: processed_czi_images, 
        abba_projects_by_animal_dir: 'H:/fullsize/fullsize',
        file_derivatives_dirname: qupath
      }, 
      {
        cohort_name: cohort3, 
        id_range: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        image_dir: processed_czi_images_cohort-3, 
        abba_projects_by_animal_dir: 'D:/ReijmersLab/TEL/slides/ABBA_projects/byAnimal',
        file_derivatives_dirname: null
      }, 
      {
        cohort_name: cohort4, 
      id_range: [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69], 
      image_dir: processed_czi_images_cohort-4,
      abba_projects_by_animal_dir: 'D:/ReijmersLab/TEL/slides/ABBA_projects/byAnimal',
      file_derivatives_dirname: null
      }
    ]
  },

  # ImgDB CONFIG
  ##########################################################################################################################################
  # TODO
  ##########################################################################################################################################

  ImgDB: {
    image_channels: [
      {name: Dapi, ch_idx: 2, colocal_id: 0}, 
      {name: GFP, ch_idx: 1, colocal_id: 2}, 
      {name: Zif, ch_idx: 0, colocal_id: 1}
    ], 
    colocal_nuclei_info: [
      {name: GFP+Zif, ch_idx: [0, 1], co_ids: [1, 2], colocal_id: 3}, 
      {name: GFP+Zif+Dapi, ch_idx: [2, 0, 1], co_ids: [0, 1, 2], colocal_id: 4}
    ], 
    normalization_params: {
      cohort2: {'0': {nmin: 20, nmax: 99.8}, '1': {nmin: 20, nmax: 99.8}, '2': {nmin: 20, nmax: 99.8}},
      cohort3: {'0': {nmin: 30, nmax: 99.8}, '1': {nmin: 30, nmax: 99.8}, '2': {nmin: 20, nmax: 99.8}}, 
      cohort4: {'0': {nmin: 30, nmax: 99.8}, '1': {nmin: 30, nmax: 99.8}, '2': {nmin: 20, nmax: 99.8}}
    }, 
    threshold_params: {
      cohort2: {
        '0': {intensity_mean: [1, null], area: [50, 1000], axis_major_length: [8, 85], axis_minor_length: [ 7, 31], eccentricity: [null, 2.9]}, 
        '1': {intensity_mean: [50, null], area: [50, 1000], axis_major_length: [7, 85], axis_minor_length: [7, 31], eccentricity: [null, 2.9]}, 
        '2': {intensity_mean: [20, null], area: [130, 1000], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [ null, 2.9]}, 
        '3': {intensity_mean: [20, null], area: [130, 850], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [null, 2.9], ch0_intensity: [75, null], intersection_percent: [0.33, null]}, 
        '4': {intensity_mean: [20, null], area: [130, 850], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [null, 2.9], ch0_intensity: [75, null], ch2_intensity: [89, null], intersection_percent: [0.33, null]}}, 
            
      cohort3: {
        '0': {intensity_mean: [1, null], area: [50, 1000], axis_major_length: [8, 85], axis_minor_length: [7, 31], eccentricity: [null, 2.9]}, 
        '1': {intensity_mean: [85, null], area: [50, 1000], axis_major_length: [7, 85], axis_minor_length: [7, 31], eccentricity: [null, 2.9]},
        '2': {intensity_mean: [45, null], area: [130, 1000], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [null, 2.9]}, 
        '3': {intensity_mean: [45, null], area: [130, 850], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [null, 2.9], ch0_intensity: [85, null], intersection_percent: [0.33, null]}
      }, 
            
      cohort4: {
        '0': {intensity_mean: [1, null], area: [50, 1000], axis_major_length: [8, 85], axis_minor_length: [7, 31], eccentricity: [null, 2.9]}, 
        '1': {intensity_mean: [100, null],area: [50, 1000], axis_major_length: [7, 85], axis_minor_length: [7, 31],eccentricity: [null, 2.9]}, 
        '2': {intensity_mean: [25, null], area: [130,1000], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [null, 2.9]}, 
        '3': {intensity_mean: [25, null], area: [130, 850], axis_major_length: [12, 85], axis_minor_length: [8, 31], eccentricity: [null, 2.9], ch0_intensity: [100, null], intersection_percent: [0.33, null]}}}}}
